  GNU nano 8.7                   .github/workflows/pipeline.yml                    Modified
gerar_codigo
        run: |
          # TODO: Gere um numero aleatorio e o salve em GITHUB_ENV como BUILD_HASH
          # Exemplo: RANDOM_NUM=$RANDOM
          # echo "BUILD_HASH=$RANDOM_NUM" >> $GITHUB_ENV
          echo "BUILD_HASH=VALOR_GERADO_AQUI" >> $GITHUB_ENV # Placeholder

      - name: "Passo 5: Usar Codigo Dinamico"
        run: |
          # TODO: Imprima o BUILD_HASH gerado no passo anterior
          echo "O hash gerado para este build foi: [VALOR_DO_HASH]"

  deploy_app:
    name: Deploy da Aplicacao
    runs-on: ubuntu-latest
    needs: build_app # Este job depende do job 'build_app'

    steps:
      - name: "Passo 6: Acessando Secrets e Vars"
        run: |

^G Help        ^O Write Out   ^F Where Is    ^K Cut         ^T Execute     ^C Location
^X Exit        ^R Read File   ^\ Replace     ^U Paste       ^J Justify     ^/ Go To Line
